name: 'docs-gen'

trigger:
  branches:
    include:
    - master
    - refs/tags/*
    
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:
- task: UseDotNet@2
  displayName: Use dotnet core SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- task: DotNetCoreCLI@2
  displayName: Install cake.tool
  inputs:
    command: 'custom' # Options: build, push, pack, publish, restore, run, test, custom
    custom: 'tool'
    arguments: 'install --tool-path dotnet-tools Cake.Tool'

- task: CmdLine@1
  displayName: Build.cake
  inputs:
    filename: 'dotnet-tools\dotnet-cake.exe'
    arguments: 'build.cake -artifactsDir=$(Build.ArtifactStagingDirectory) -configuration=$(buildConfiguration)'

#- task: CmdLine@1
#  displayName: Benchmarks
#  inputs:
#    filename: 'dotnet-tools\dotnet-cake.exe'
#    arguments: 'build.cake -target=Benchmarks'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    searchFolder: '$(Build.ArtifactStagingDirectory)'
    testResultsFiles: '**/*.trx' 
    mergeTestResults: false

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathtoPublish: 'BenchmarkDotNet.Artifacts' 
#    artifactName: 'benchmarks' 

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'artifacts' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
