name: on-tag-do-release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: mandatory for ncipollo/release-action to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
